import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { searchComponents } from '../src/core/search'
import { getRelative, snakeToCamel } from '../src/core/utils'
import { getDeclaration } from '../src/core/declaration'
import { genDeclaration } from '../src/core'
import { VkUviewUiResolver } from '../src/resolvers/vkUviewUi'

describe('index', () => {
  it('hi vitest', () => {
    expect(1).toBe(1)
  })
  it('search components', () => {
    expect(
      searchComponents(path.join(__dirname, '../playground/src/components')),
    ).toStrictEqual(['a-comp/a-comp.vue'])
  })
  it('snake to camel', () => {
    expect(snakeToCamel('a-comp')).toBe('AComp')
  })
  it('declaration', () => {
    expect(
      getDeclaration({
        AComp: 'a-comp/a-comp.vue',
      }, 'src/components/'),
    ).toMatchInlineSnapshot(`
      "/* eslint-disable */
      // @ts-nocheck
      // Generated by @wyatex/unplugin-gen-uniapp-components-dts
      export {}

      /* prettier-ignore */
      declare module 'vue' {
        interface GlobalComponents {
          AComp: typeof import('src/components/a-comp/a-comp.vue')['default']
        }
      }
      "
    `)
  })
  it('computed relative', () => {
    expect(getRelative('./components.d.ts', 'src/components/')).toBe('./src/components/')
    expect(getRelative('src/types/components.d.ts', 'src/components/')).toBe('./../components/')
  })
  it('gen dts', () => {
    expect(genDeclaration({
      dtsPath: './playground/src/types/components.d.ts',
      resolvers: [],
    }, './playground/src/components')).toMatchInlineSnapshot(`
      "/* eslint-disable */
      // @ts-nocheck
      // Generated by @wyatex/unplugin-gen-uniapp-components-dts
      export {}

      /* prettier-ignore */
      declare module 'vue' {
        interface GlobalComponents {
          AComp: typeof import('./../components/a-comp/a-comp.vue')['default']
        }
      }
      "
    `)
  })
  
})
