/* eslint-disable */
// @ts-nocheck
// Generated by @wyatex/unplugin-gen-uniapp-components-dts
export {}

/* prettier-ignore */
declare module 'vue' {
  interface GlobalComponents {
    AComp: typeof import('./../components/a-comp/a-comp.vue')['default']
  }
}
